apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-python-deployment
  labels:
    app: myapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: app-container
          image: acrsanjay1.azurecr.io/my-python-app-sanjay:v1
          ports:
            - containerPort: 8000