apiVersion: v1
kind: Service
metadata:
  name: my-app-service
  labels:
    app: myapp
spec:
  selector:
    app: myapp
  type: LoadBalancer   # or ClusterIP / NodePort
  ports:
    - protocol: TCP
      port: 8000         # Port exposed by the service
      targetPort: 8000   # Port on the container
